### ISSUE TITLE
How to run a single tag only?

### ISSUE THREAD

**Issue by tgsmith61591** [cucumber-rs/cucumber#156]
The [doc suggests](https://cucumber-rs.github.io/cucumber/current/Features.html#cli-options) running a subset of tags works. However, I cannot get this to work in my Cucumber project:

```bash
❯ cargo test -- --tags='@music'
...
error: Unrecognized option: 'tags'
```

How can I select which tag to run?

**Comment by ilslv** [comment]
@tgsmith61591 first of all please provide version you are using

Our docs say following:

> Example with tag expressions for filtering Scenarios:

```
cargo test --test <test-name> -- --tags='@cat or @dog or @ferris'
```

Note existence of `--test <test-name>`. It's required to specify single Rust test to run, while running `cargo test -- --tags='@cat or @dog or @ferris'` tries to execute all existing tests, which can be unit or doc tests. They don't know nothing about cucumber cli options.

**Comment by tgsmith61591** [comment]
I'm on version 0.9.0. Once I provided `<test-name>`, I've begun to get a different error.

Here is my `Cargo.toml`:

```toml
[package]
name = "foo_package"
# ...

[[test]]
name = "cucumber"
harness = false

# ...

[dev-dependencies]
cucumber_rust = "0.9.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread", "macros", "time"] }

```

To trigger the test: `$ cargo test --test cucumber -- --tags='@music'`, results in a new error:

```bash
error: Found argument '--tags' which wasn't expected, or isn't valid in this context
```
